# Step 1: Use an official Node.js image as a build image
FROM node:16 AS build

# Step 2: Set the working directory inside the container
WORKDIR /app

# Step 3: Copy package.json and package-lock.json to the container
COPY package*.json ./

# Step 4: Install dependencies
RUN npm install

# Step 5: Copy the rest of the application code into the container
COPY . .

# Step 6: Build the Angular app for production
RUN npm run build --prod

# Step 7: Use an official Nginx image to serve the app
FROM nginx:alpine

# Step 8: Copy the built Angular app from the 'dist' directory to Nginx's default folder
COPY --from=build /app/dist/hadiya_products_admin /usr/share/nginx/html

# Step 9: Expose port 80 for Nginx
EXPOSE 80

# Step 10: Start Nginx
CMD ["nginx", "-g", "daemon off;"]
